__default__:
  job-name: "{rule}-{wildcards.sample}"
  partition: short
  time: 60 # minutes
  nodes: 1
  ntasks: 4
  mem: 32gb
  output: "log/{rule}-{wildcards.sample}-%j.out"
  error: "log/{rule}-{wildcards.sample}-%j.err"

CreateIndex:
  partition: long
  time: 10080 # 1 week
  ntasks: 64
  mem: 256gb # probably overkill (nope...)

Bwapairedsample:
  partition: short
  time: 1439 # almost 24hrs
  mem: 64gb
  ntasks: 64
