__default__:
  job-name: "{rule}"
  partition: short
  time: 60 # minutes
  nodes: 1
  ntasks: 4
  mem: 32gb
  output: "log/{rule}-%j.out"
  error: "log/{rule}-%j.err"

CreateIndex:
  partition: long
  time: 10080 # 1 week
  ntasks: 64
  mem: 512gb # probably overkill (nope...)

Bwapairedsample:
  partition: short
  time: 1439 # almost 24hrs
  mem: 64gb
  ntasks: 64

QueryIndex:
  job-name: "{rule}"
  partition: long
  time: 10080
  ntasks: 64
  mem: 256gb

Fastq2Fasta:
  job-name: "{rule}"
  partition: short
  time: 120
  ntasks: 1

BwaIndex:
  job-name: "{wildcards.seq}-{rule}"
  partition: long
  time: 10080 #minutes
  mem: 128gb
  ntasks: 1
  output: "log/{rule}-{wildcards.seq}-%j.out"
  error: "log/{rule}-{wildcards.seq}-%j.err"

BwaMem:
  job-name: "{wildcards.sample}-{wildcards.seq}-{rule}"
  partition: short
  time: 120 #minutes
  ntasks: 64
  mem: 64gb
  output: "log/{rule}-{wildcards.sample}-{wildcards.seq}-%j.out"
  error: "log/{rule}-{wildcards.sample}-{wildcards.seq}-%j.err"
